import type { FeaturedItem, Shoe } from './types';

const shoes: Shoe[] = [
  {
    id: 1,
    name: "APEX RUNNER X1",
    price: "$189",
    tag: "NEW DROP",
    tagColor: "#ff3c3c",
    color: "#FF6B35",
    bg: "from-orange-950 via-orange-900 to-stone-950",
    accent: "#FF6B35",
    desc: "Engineered for the streets. Built for legends.",
    emoji: "FIRE",
    svg: "orange",
    image: "/shoes/jordan2.png",
  },
  // {
  //   id: 2,
  //   name: "STEALTH ELITE",
  //   price: "$224",
  //   tag: "BESTSELLER",
  //   tagColor: "#3caaff",
  //   color: "#3CAAFF",
  //   bg: "from-blue-950 via-slate-900 to-black",
  //   accent: "#3CAAFF",
  //   desc: "Silent steps. Loud presence.",
  //   emoji: "BOLT",
  //   svg: "blue",
  //   image: "/shoes/jordan2.png",
  // },
  // {
  //   id: 3,
  //   name: "VAPOR CLOUD 3",
  //   price: "$167",
  //   tag: "LIMITED",
  //   tagColor: "#b03cff",
  //   color: "#B03CFF",
  //   bg: "from-purple-950 via-violet-900 to-black",
  //   accent: "#B03CFF",
  //   desc: "Walk on air. Leave a mark.",
  //   emoji: "SPARK",
  //   svg: "purple",
  //   image: "/shoes/jordan2.png",
  // },
  // {
  //   id: 4,
  //   name: "TERRA GRIP PRO",
  //   price: "$198",
  //   tag: "ECO SERIES",
  //   tagColor: "#3cff8a",
  //   color: "#3CFF8A",
  //   bg: "from-green-950 via-emerald-900 to-stone-950",
  //   accent: "#3CFF8A",
  //   desc: "Tread lightly. Dominate wildly.",
  //   emoji: "LEAF",
  //   svg: "green",
  //   image: "/shoes/jordan2.png",
  // },
  {
    id: 5,
    name: "JORDAN BLUE",
    price: "$209",
    tag: "NEW IMAGE",
    tagColor: "#3caaff",
    color: "#3CAAFF",
    bg: "from-blue-950 via-slate-900 to-black",
    accent: "#3CAAFF",
    desc: "Fresh colorway in the carousel lineup.",
    emoji: "BOLT",
    svg: "blue",
    image: "/shoes/jordan blue.png",
    imageScale: 1.2,
    imageOffsetY: 0,
  },
];

const featured: FeaturedItem[] = [
  {
    name: "APEX RUNNER X1",
    price: "$189",
    color: "#FF6B35",
    desc: "Streets Edition",
    tag: "NEW",
  },
  {
    name: "STEALTH ELITE",
    price: "$224",
    color: "#3CAAFF",
    desc: "Performance Series",
    tag: "HOT",
  },
  {
    name: "VAPOR CLOUD 3",
    price: "$167",
    color: "#B03CFF",
    desc: "Comfort Plus",
    tag: "LTD",
  },
  {
    name: "TERRA GRIP PRO",
    price: "$198",
    color: "#3CFF8A",
    desc: "Trail Ready",
    tag: "ECO",
  },
  {
    name: "NOCTURNE SLIP",
    price: "$145",
    color: "#FFD13C",
    desc: "Night Walk",
    tag: "SALE",
  },
  {
    name: "MONO FORCE",
    price: "$212",
    color: "#FF3C8A",
    desc: "Urban Core",
    tag: "NEW",
  },
];

export { shoes, featured };

